### ISSUE TITLE
banner resizing

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/megamek.github.io#2]
The banner image at the top can look weird at full screen on high resolutions because it is basically zooming in on a 350px fixed height slice. I think we might be able to fix this by resizing the original image and then cropping to a 350px band.

**Comment by rjhancock** [comment]
How about using media queries to adjust the quality of the image based on width. The fact it's being cropped isn't really too much of an issue, but we can bring the file size down based on screen size to cut bandwidth for those on mobile or other limited connections.

**Comment by AaronGullickson** [comment]
That seems like a good idea as well. My original concern was that when you go full screen on a computer with good resolution, you end up getting a cross section of torsos - but I am becoming less and less concerned with that issue.

**Comment by rjhancock** [comment]
It does bother me at that size but this isn't the only site that does it. Best to plan for a 1080p (or less) screen as that's the most common.

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/megamek.github.io/commit/bc75fc2242ea6cdf18f8d0b018f6f437f7d23a53
