### ISSUE TITLE
Website: downloads page typo: "combat" is spelled "comabt"

### ISSUE THREAD

**Issue by Felderburg** [MegaMek/megamek.github.io#32]
Not sure if this is the appropriate place to put this, but none of the megamek repositories seemed to fit, so here we are.

### Environment
MegaMek website, downloads page (https://megamek.org/downloads.html)

### Description
"combat" is misspelled as "comabt" in the top description of MekHQ.

### Files
N/A

**Comment by sixlettervariables** [comment]
I moved it to the website's repository. Appreciate it!

**Comment by Felderburg** [comment]
> I moved it to the website's repository. Appreciate it!

Sounds good. Based on the title/description I thought this repository was for github only, thanks for the clarification. (I should have scrolled down and looked at the readme, I guess)

**Comment by sixlettervariables** [comment]
No worries. Closed via #34
